show_on:
  default: discovery
  type: enum
  choices:
    - discovery
    - homepage
    - all
  description: discovery refers to topic list pages

max_trust_level:
  type: integer
  default: 1
  max: 5
  description: Show for this trust level and below; set 5 for all

hide_for_staff:
  default: false

hide_on_mobile:
  default: false

hide_for_anon:
  default: false
  description: hide the banner for logged-out users

banner_background_image:
  type: upload
  default: ""

mobile_banner_background_image:
  type: upload
  default: ""

banner_background_repeat:
  type: enum
  default: no-repeat
  choices:
    - no-repeat
    - repeat
    - repeat-x
    - repeat-y

banner_background_size:
  type: string
  default: cover
  description: uses <a href="https://developer.mozilla.org/en-US/docs/Web/CSS/background-size">CSS background size property</a>

banner_background_color:
  type: string
  default: "var(--tertiary-low)"

svg_icons:
  default: "user-friends"
  type: "list"
  list_type: "compact"

layout:
  default: "text-left"
  type: "enum"
  choices:
    - "text-left"
    - "text-top"

plugin_outlet:
  default: "above-site-header"
  type: "enum"
  choices:
    - "below-site-header"
    - "above-main-container"
  description: changes the banner position, use "above-main-container" if you have the sidebar enabled
